### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by chrzyki**
WIP:

- [ ] check orthography issues
- [ ] check/verify changes to `FormTable`

### CODE REVIEW

**Comment by FredericBlum** [comment]
Looks like the transcription errors come through some comment that is added after "__"? PUA is probably Proto-Uta-Aztecan, and SUA SOuthern-Uto-Aztecan. I would propose to just add a replacement to the lexibank script and remove those cases

**Review by FredericBlum — APPROVED** [review]

**Comment by chrzyki** [comment]
Yeah, I was just curious where they came from.

**Comment by chrzyki** [comment]
@FredericBlum fixed.

**Comment by LinguList** [comment]
I remember that I had accounted for all cases, as I was discussing with @maunus, so let me check quickly later.

**Comment by LinguList** [comment]
In fact: I had handled `_SUA` and `_PUA` via `etc/lexemes.tsv`. I do not know why it is necessary to now replace the lexeme as well. Can we please make sure to check the cases?

**Comment by chrzyki** [comment]
Thanks for checking. Yes, I'll have a look!

**Comment by LinguList** [comment]
Just pushed the change: two lines more in lexemes.tsv, seems more 
transparent in this case!

**Comment by chrzyki** [comment]
Awesome, thanks! I'll do a re-run.

**Comment by chrzyki** [comment]
> Just pushed the change: two lines more in lexemes.tsv, seems more transparent in this case!

Yeah, thanks for catching that. Sorry, I had a little brain fog during the fixes, lexeme changes are definitely more transparent. Thanks!

**Comment by Maunus** [comment]
It is not entirely clear to me what it is we are fixing here and how (it's been a while), but let me know if there is something I can help with.

**Pull request merged**
